version: '2'

services:
  hadoop-master:
    container_name: hadoop-master
    hostname: hadoop-master
    mem_limit: 4000m
    entrypoint :
      - "sh"
      - "-c"
      - "service ssh start; tail -f /dev/null"
    build: .
    volumes:
      - ./data:/root/shared
    ports:
      # port for namenode
      - "50070:50070"
      # port for web ui REsourceManager
      - "8088:8088"
      # port for hbase
      - "16010:16010"
      # port for web ui spark properties
      - "4040:4040"
      # port for web ui spark master
      - "8080:8080"
      # port for hadoop-master
      - "9000:9000"
      # port for kafka-rest proxy
      - "18082:18082"
      # port for yarn resource manager
      - "8032:8032"
      # port for yarn scheduler 
      - "8030:8030"
    networks:
      bdnetwork:
        ipv4_address: 172.18.0.2
    extra_hosts:
      - "hadoop-slave1:172.18.0.3"
      - "hadoop-slave2:172.18.0.4"
      - "graphite-server:172.18.0.5" 

  hadoop-slave1:
    container_name: hadoop-slave1
    hostname: hadoop-slave1
    mem_limit: 4000m
    entrypoint :
      - "sh"
      - "-c"
      - "rm /var/zookeeper_data/myid; echo \"1\" >/var/zookeeper_data/myid; service ssh start ;/usr/local/derby/bin/startNetworkServer -h hadoop-slave1;tail -f /dev/null"
    
    build: .
    volumes:
      - ./data:/root/shared
    ports:
      #port for web ui of spark worker
      - "8081:8081"
    networks:
      bdnetwork:
        ipv4_address: 172.18.0.3
    extra_hosts:
      - "hadoop-master:172.18.0.2"
      - "hadoop-slave2:172.18.0.4"
      - "graphite-server:172.18.0.5"

  hadoop-slave2:
    container_name: hadoop-slave2
    hostname: hadoop-slave2
    mem_limit: 4000m
    entrypoint :
      - "sh"
      - "-c"
      - "service ssh start;rm /var/zookeeper_data/myid; echo \"2\" >/var/zookeeper_data/myid; tail -f /dev/null"
    build: .
    volumes:
      - ./data:/root/shared
    ports:
      #ports for web ui of spark worker
      - "8082:8081"
      #port for shcema-resitry
      - "18081:18081" 
    networks:
      bdnetwork:
        ipv4_address: 172.18.0.4
    extra_hosts:
      - "hadoop-master:172.18.0.2"
      - "hadoop-slave1:172.18.0.3"
      - "graphite-server:172.18.0.5"

  graphite-server:
    container_name: graphite-server
    hostname: graphite-server
    mem_limit: 1000m
    build: ./fullgraphite
    entrypoint :
      - "sh"
      - "-c"
      - "/usr/bin/supervisord; tail -f /dev/null"
    networks:
      bdnetwork:
        ipv4_address: 172.18.0.5
    extra_hosts:
      - "hadoop-master:172.18.0.2"
      - "hadoop-slave1:172.18.0.3"
      - "hadoop-slave2:172.18.0.4"
   
networks:
  bdnetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

