version: '2'

services:
  hadoop-master:
    container_name: hadoop-master
    entrypoint :
      - "sh"
      - "-c"
      - "service ssh start; tail -f /dev/null"
    build: .
    volumes:
      - ./data:/root/shared
    ports:
      # port for namenode
      - "50070:50070"
      # port for web ui REsourceManager
      - "8088:8088"
      # port for hbase
      - "16010:16010"
      # port for web ui spark properties
      - "4040:4040"
      # port for web ui spark master
      - "8080:8080"
     

  hadoop-slave1:
    container_name: hadoop-slave1
    entrypoint :
      - "sh"
      - "-c"
      - "service ssh start; tail -f /dev/null"
    
    build: .
    volumes:
      - ./data:/root/shared
    ports:
      #port for web ui of spark worker
      - "8081:8081"


  hadoop-slave2:
    container_name: hadoop-slave2
    entrypoint :
      - "sh"
      - "-c"
      - "service ssh start; tail -f /dev/null"
    build: .
    volumes:
      - ./data:/root/shared
    ports:
      #ports for web ui of spark worker
      - "8082:8081"

   
